# Server Identity
server_name: "nats-leaf-2a"

# Network Configuration
port: 4227

# Local JetStream
jetstream {
    domain: leaf-2
    store_dir: "/data/jetstream"
    max_memory_store: 512MB
    max_file_store: 5GB
}

# leaf Clustering Configuration
cluster {
    name: "leaf-2-cluster"
    port: 6227
    routes: [
        "nats://<LEAF_HOST_2b>:6228"
    ]
}

# Leafnode Configuration
leafnodes {
    remotes = [
        {
            urls: [
                "nats://<HUB_HOST_1>:7422",
                "nats://<HUB_HOST_2>:7423",
                "nats://<HUB_HOST_3>:7424"
            ]
            account: "<APP_ACCOUNT_ID>"  # app account
            credentials: "/etc/nats/creds/exec_user.creds" # exec_user from app account for connection
        }
    ]
    reconnect: 1s
}

# HTTP Monitoring
http_port: 8227

operator: <OPERATOR_JWT>
# System Account named SYS
system_account: <SYSTEM_ACCOUNT_ID>

resolver: MEMORY

resolver_preload: {
    #system account
	<SYSTEM_ACCOUNT_ID>: <SYSTEM_ACCOUNT_JWT>,

    <APP_ACCOUNT_ID>: <APP_ACCOUNT_JWT>
}