# Server Identity
server_name: "nats-hub-3"

# Network Configuration
port: 4224

# Hub Clustering Configuration
cluster {
    name: "hub-cluster"
    port: 6224

    authorization {
    user: route_user
    password: route_password
    timeout: 0.5
  }

    routes: [
        "nats://route_user:route_password@<HUB_HOST_1>:6222",
        "nats://route_user:route_password@<HUB_HOST_2>:6223"
    ]
}

jetstream: {
    domain: hub
    store_dir: "/data/jetstream"
    max_mem_store: 1Gb
    max_file_store: 10Gb
}

# Leafnode Configuration for Hub
leafnodes {
    port: 7424
}

# System Account Configuration
system_account: SYS

accounts: {
    app: {
        jetstream: enabled
        
        users: [
            {
                user: "backend_user",
                password: "backend_password",
                permissions: {
                    publish: ">",
                    subscribe: ">"
                }
            },
            {
                user: "exec_user",
                password: "exec_password",
                permissions: {
                    publish: ">",
                    subscribe: ">"
                }
            }
        ]
    },
    SYS: {
        users: [
            {
                user: "sys",
                password: "sys_password",
                permissions: {
                    publish: ">",
                    subscribe: ">",
                    allow_responses: true
                }
            }
        ]
    }
}


websocket: {
    port: 8444
    no_tls: true
}

# HTTP Monitoring
http_port: 8224
