# Server Identity
server_name: "nats-hub-2"

# Network Configuration
port: 4223

jetstream: {
    domain: hub
    store_dir: "/data/jetstream"
    max_mem_store: 1Gb
    max_file_store: 10Gb
}

# Hub Clustering Configuration
cluster {
    name: "hub-cluster"
    port: 6223

    routes: [
        "nats://<HUB_HOST_1>:6222",
        "nats://<HUB_HOST_3>:6224"
    ]
}

# Leafnode Configuration for Hub
leafnodes {
    port: 7423
}

operator: <OPERATOR_JWT>
# System Account named SYS
system_account: <SYSTEM_ACCOUNT_ID>

# configuration of the nats based resolver
resolver {
    type: full
    dir: '/data/jwt'
    allow_delete: true
    interval: "2m"
    timeout: "1.9s"
}

resolver_preload: {
    #system account
	<SYSTEM_ACCOUNT_ID>: <SYSTEM_ACCOUNT_JWT>
}

websocket: {
    port: 8443
    no_tls: true
}

# HTTP Monitoring
http_port: 8223